{application,vortex_indexer,
             [{description,"vortex_indexer"},
              {vsn,"1"},
              {modules,[vortex_indexer,vortex_indexer_app,
                        vortex_indexer_dwarf,vortex_indexer_sup]},
              {registered,[]},
              {applications,[kernel,stdlib,riakc,inets,crypto,mochiweb]},
              {mod,{vortex_indexer_app,[]}},
              {env,[]}]}.
